version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions:"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "all:"
    open-pull-requests-limit: 15
  - package-ecosystem: "pub"
    directory: "/flutter"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "flutter:"
    open-pull-requests-limit: 15
  - package-ecosystem: "gitsubmodule"
    directories:
      - "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "all:"
    open-pull-requests-limit: 5
