version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions:"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "all:"
    open-pull-requests-limit: 15
    groups:
      dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch"]
