package org.ole.planet.myplanet.model.dto

data class NewsItem(
    val id: String,
    val _id: String?,
    val message: String?,
    val time: Long,
    val userName: String?,
    val userId: String?,
    val isEdited: Boolean,
    val sharedBy: String?,
    val imageUrls: List<String>,
    val libraryImages: List<String>,
    val labels: List<String>,
    val viewIn: String?,
    val newsId: String?,
    val conversations: String?,
    val isCommunityNews: Boolean,
    val replyTo: String?,
    val userImage: String?,
    val userFullName: String?,
    val canEdit: Boolean,
    val canDelete: Boolean,
    val canReply: Boolean,
    val canAddLabel: Boolean,
    val canShare: Boolean,
    val replyCount: Int,
    val sharedTeamName: String,
    val docType: String?,
    val avatar: String?,
    val messagePlanetCode: String?,
    val messageType: String?,
    val parentCode: String?,
    val createdOn: String?,
    val user: String?,
    val images: String?,
    val newsRev: String?,
    val newsUser: String?,
    val aiProvider: String?,
    val newsTitle: String?,
    val newsCreatedDate: Long,
    val newsUpdatedDate: Long,
    val chat: Boolean,
    val editedTime: Long,
    var resolvedLibraryImagePaths: List<String> = emptyList()
)
