package org.ole.planet.myplanet.ui.team


enum class TeamPage {
    CHAT, PLAN, MISSION, TEAM, MEMBERS, TASKS, CALENDAR, SURVEY,
    COURSES, FINANCES, REPORTS, DOCUMENTS, RESOURCES, APPLICANTS, JOIN_REQUESTS
}

