# Tag last commit as 'version in string.xml document'.

if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
  git config --global user.email "leomaxi@outlook.com"
  git config --global user.name "leomaxi"

  git remote add release "https://${GH_TOKEN}@github.com/ole-vi/takeout.git"
  PACKAGE_VERSION=$(sed -n 's/.*name="app_version">\([^"]*\).*<\/string>/\1/p' < ../app/src/main/res/values/strings.xml)
  git push -d release latest
  git tag -d latest
  git tag -a PACKAGE_VERSION -m "[Autogenerated] This is the latest version pushed to the master branch."
  git push release --tags
  echo -e "Done with tags.\n"
fi