package org.ole.planet.myplanet.model

data class NewsItem(
    val id: String?,
    val_id: String?,
   val_rev: String?,
    val userId: String?,
    val user: String?,
    val message: String?,
    val docType: String?,
    val viewableBy: String?,
    val viewableId: String?,
    val avatar: String?,
    val replyTo: String?,
    val userName: String?,
    val messagePlanetCode: String?,
    val messageType: String?,
    val updatedDate: Long = 0,
    val time: Long = 0,
    val createdOn: String?,
    val parentCode: String?,
    val imageUrls: List<String>?,
    val images: String?,
    val labels: List<String>?,
    val viewIn: String?,
    val newsId: String?,
    val newsRev: String?,
    val newsUser: String?,
    val aiProvider: String?,
    val newsTitle: String?,
    val conversations: String?,
    val newsCreatedDate: Long = 0,
    val newsUpdatedDate: Long = 0,
    val chat: Boolean = false,
    val isEdited: Boolean = false,
    val editedTime: Long = 0,
    val sharedBy: String?,
    val formattedUpdatedDate: String,
    val formattedTime: String,
    val formattedNewsCreatedDate: String,
    val formattedNewsUpdatedDate: String,
    val isCommunityNews: Boolean = false
)
